from __future__ import annotations


DEMO_SOURCE = "dach_demo_fixture"


DACH_DEMO_FIXTURES = [
    {
        "notice_id": "DE-DEMO-001",
        "title": "Demo road maintenance framework",
        "buyer": "Demo German municipal roads team",
        "country": "Germany",
        "region": "North Rhine-Westphalia",
        "deadline": "2026-08-12",
        "value": "1800000",
        "currency": "EUR",
        "cpv": ["45233141", "45233142"],
        "url": "fixture://dach/germany/road-maintenance",
        "source": DEMO_SOURCE,
        "published_at": "2026-07-01",
        "description": "Fixture-only road infrastructure term contract for recurring maintenance and construction repair testing.",
        "procurement_stage": "open",
    },
    {
        "notice_id": "DE-DEMO-002",
        "title": "Demo bridge repair and concrete works",
        "buyer": "Demo German infrastructure authority",
        "country": "Germany",
        "region": "Bavaria",
        "deadline": "2026-08-28",
        "value": 2750000,
        "currency": "EUR",
        "cpv": "45221119",
        "url": "fixture://dach/germany/bridge-repair",
        "source": DEMO_SOURCE,
        "published_at": "2026-07-02",
        "description": "Fixture-only bridge repair with concrete civil engineering works for DACH adapter testing.",
        "procurement_stage": "open",
    },
    {
        "notice_id": "DE-DEMO-003",
        "title": "Demo general estate maintenance package",
        "buyer": "Demo German local works department",
        "country": "Germany",
        "region": "Hesse",
        "deadline": "2026-11-20T12:00:00",
        "value": "",
        "currency": "EUR",
        "cpv": ["50000000"],
        "url": "fixture://dach/germany/general-maintenance",
        "source": DEMO_SOURCE,
        "published_at": "2026-07-03",
        "description": "Fixture-only mixed maintenance notice with unclear construction scope for DACH adapter testing.",
        "procurement_stage": "open",
    },
    {
        "notice_id": "AT-DEMO-001",
        "title": "Demo school refurbishment works",
        "buyer": "Demo Austrian school estate team",
        "country": "Austria",
        "region": "Vienna",
        "deadline": "2026-08-05",
        "value": "980000",
        "currency": "EUR",
        "cpv": ["45453100"],
        "url": "fixture://dach/austria/school-refurbishment",
        "source": DEMO_SOURCE,
        "published_at": "2026-07-04",
        "description": "Fixture-only school refurbishment and building works notice for DACH adapter testing.",
        "procurement_stage": "open",
    },
    {
        "notice_id": "AT-DEMO-002",
        "title": "Demo public building works",
        "buyer": "Demo Austrian public buildings unit",
        "country": "Austria",
        "region": "Styria",
        "deadline": "2026-09-18",
        "value": 420000,
        "currency": "EUR",
        "cpv": "45210000",
        "url": "fixture://dach/austria/public-building-works",
        "source": DEMO_SOURCE,
        "published_at": "2026-07-05",
        "description": "Fixture-only public building refurbishment with facilities-related construction works for DACH adapter testing.",
        "procurement_stage": "open",
    },
    {
        "notice_id": "AT-DEMO-003",
        "title": "Demo utilities maintenance contract",
        "buyer": "Demo Austrian utilities maintenance team",
        "country": "Austria",
        "region": "Upper Austria",
        "deadline": "2026-07-18",
        "value": "720000",
        "currency": "EUR",
        "cpv": ["50500000", "45259000"],
        "url": "fixture://dach/austria/utilities-maintenance",
        "source": DEMO_SOURCE,
        "published_at": "2026-07-06",
        "description": "Fixture-only utilities maintenance and infrastructure repair notice for DACH adapter testing.",
        "procurement_stage": "open",
    },
    {
        "notice_id": "CH-DEMO-001",
        "title": "Demo wastewater infrastructure works",
        "buyer": "Demo Swiss wastewater infrastructure team",
        "country": "Switzerland",
        "region": "Zurich",
        "language": "de",
        "deadline": "2026-08-15",
        "value": "2100000",
        "currency": "CHF",
        "cpv": ["45232420"],
        "url": "fixture://dach/switzerland/wastewater-infrastructure",
        "source": DEMO_SOURCE,
        "published_at": "2026-07-07",
        "description": "Fixture-only wastewater and drainage infrastructure construction works notice for DACH adapter testing.",
        "procurement_stage": "open",
    },
    {
        "notice_id": "CH-DEMO-002",
        "title": "Demo mixed framework maintenance agreement",
        "buyer": "Demo Swiss municipal maintenance group",
        "country": "Switzerland",
        "region": "Bern",
        "language": "de",
        "deadline": "2026-10-25",
        "value": "120000",
        "currency": "CHF",
        "cpv": ["45233139"],
        "url": "fixture://dach/switzerland/framework-maintenance",
        "source": DEMO_SOURCE,
        "published_at": "2026-07-08",
        "description": "Fixture-only mixed framework maintenance notice with limited civil engineering detail for DACH adapter testing.",
        "procurement_stage": "open",
    },
    {
        "notice_id": "CH-DEMO-003",
        "title": "Demo concrete and civil engineering works",
        "buyer": "Demo Swiss civil engineering unit",
        "country": "Switzerland",
        "region": "Vaud",
        "language": "fr",
        "deadline": "2026-06-20",
        "value": 3400000,
        "currency": "CHF",
        "cpv": ["45262300", "45220000"],
        "url": "fixture://dach/switzerland/concrete-civils",
        "source": DEMO_SOURCE,
        "published_at": "2026-07-09",
        "description": "Fixture-only concrete and civil engineering infrastructure works notice with an intentionally stale deadline for DACH adapter testing.",
        "procurement_stage": "open",
    },
]
