from __future__ import annotations


DEMO_SOURCE = "dach_demo_fixture"


DACH_DEMO_FIXTURES = [
    {
        "notice_id": "DE-DEMO-001",
        "title": "Demo road maintenance package",
        "buyer": "Demo German municipal roads team",
        "country": "Germany",
        "region": "North Rhine-Westphalia",
        "deadline": "2026-09-15",
        "value": "1250000",
        "currency": "EUR",
        "cpv": ["45233141", "45233142"],
        "url": "fixture://dach/germany/road-maintenance",
        "source": DEMO_SOURCE,
        "published_at": "2026-07-01",
        "description": "Fixture-only road maintenance notice for DACH adapter testing.",
        "procurement_stage": "open",
    },
    {
        "notice_id": "DE-DEMO-002",
        "title": "Demo bridge repair works",
        "buyer": "Demo German infrastructure authority",
        "country": "Germany",
        "region": "Bavaria",
        "deadline": "15.10.2026",
        "value": 2750000,
        "currency": "EUR",
        "cpv": "45221119",
        "url": "fixture://dach/germany/bridge-repair",
        "source": DEMO_SOURCE,
        "published_at": "2026-07-02",
        "description": "Fixture-only bridge repair notice for DACH adapter testing.",
        "procurement_stage": "open",
    },
    {
        "notice_id": "DE-DEMO-003",
        "title": "Demo drainage works programme",
        "buyer": "Demo German local works department",
        "country": "Germany",
        "region": "Hesse",
        "deadline": "2026-11-03T12:00:00",
        "value": "640000",
        "currency": "EUR",
        "cpv": ["45232452"],
        "url": "fixture://dach/germany/drainage-works",
        "source": DEMO_SOURCE,
        "published_at": "2026-07-03",
        "description": "Fixture-only drainage works notice for DACH adapter testing.",
        "procurement_stage": "open",
    },
    {
        "notice_id": "AT-DEMO-001",
        "title": "Demo school refurbishment works",
        "buyer": "Demo Austrian school estate team",
        "country": "Austria",
        "region": "Vienna",
        "deadline": "2026-09-30",
        "value": "980000",
        "currency": "EUR",
        "cpv": ["45453100"],
        "url": "fixture://dach/austria/school-refurbishment",
        "source": DEMO_SOURCE,
        "published_at": "2026-07-04",
        "description": "Fixture-only school refurbishment notice for DACH adapter testing.",
        "procurement_stage": "open",
    },
    {
        "notice_id": "AT-DEMO-002",
        "title": "Demo public building works",
        "buyer": "Demo Austrian public buildings unit",
        "country": "Austria",
        "region": "Styria",
        "deadline": "30/10/2026",
        "value": 1800000,
        "currency": "EUR",
        "cpv": "45210000",
        "url": "fixture://dach/austria/public-building-works",
        "source": DEMO_SOURCE,
        "published_at": "2026-07-05",
        "description": "Fixture-only public building works notice for DACH adapter testing.",
        "procurement_stage": "open",
    },
    {
        "notice_id": "AT-DEMO-003",
        "title": "Demo utilities maintenance contract",
        "buyer": "Demo Austrian utilities maintenance team",
        "country": "Austria",
        "region": "Upper Austria",
        "deadline": "2026-12-01",
        "value": "720000",
        "currency": "EUR",
        "cpv": ["50500000", "45259000"],
        "url": "fixture://dach/austria/utilities-maintenance",
        "source": DEMO_SOURCE,
        "published_at": "2026-07-06",
        "description": "Fixture-only utilities maintenance notice for DACH adapter testing.",
        "procurement_stage": "open",
    },
    {
        "notice_id": "CH-DEMO-001",
        "title": "Demo wastewater infrastructure works",
        "buyer": "Demo Swiss wastewater infrastructure team",
        "country": "Switzerland",
        "region": "Zurich",
        "language": "de",
        "deadline": "2026-10-20",
        "value": "2100000",
        "currency": "CHF",
        "cpv": ["45232420"],
        "url": "fixture://dach/switzerland/wastewater-infrastructure",
        "source": DEMO_SOURCE,
        "published_at": "2026-07-07",
        "description": "Fixture-only wastewater infrastructure notice for DACH adapter testing.",
        "procurement_stage": "open",
    },
    {
        "notice_id": "CH-DEMO-002",
        "title": "Demo framework maintenance agreement",
        "buyer": "Demo Swiss municipal maintenance group",
        "country": "Switzerland",
        "region": "Bern",
        "language": "de",
        "deadline": "2026-11-18",
        "value": "1500000",
        "currency": "CHF",
        "cpv": ["45233139"],
        "url": "fixture://dach/switzerland/framework-maintenance",
        "source": DEMO_SOURCE,
        "published_at": "2026-07-08",
        "description": "Fixture-only framework maintenance notice for DACH adapter testing.",
        "procurement_stage": "open",
    },
    {
        "notice_id": "CH-DEMO-003",
        "title": "Demo concrete and civil engineering works",
        "buyer": "Demo Swiss civil engineering unit",
        "country": "Switzerland",
        "region": "Vaud",
        "language": "fr",
        "deadline": "2026-12-15",
        "value": 3400000,
        "currency": "CHF",
        "cpv": ["45262300", "45220000"],
        "url": "fixture://dach/switzerland/concrete-civils",
        "source": DEMO_SOURCE,
        "published_at": "2026-07-09",
        "description": "Fixture-only concrete and civil engineering notice for DACH adapter testing.",
        "procurement_stage": "open",
    },
]
